version: '3.8'
services:
  user-service:
    build: .
    environment:
      - PORT=3001
      - DB_URI=mongodb://mongodb:27017/blog
      - CRYPT_SALT=10
      - JWT_KEY=j5723hfgs9
      - JWT_EXPIRE=1d
      - REDIS_URI=redis://redis:6379/
      - REDIS_PORT=6379
      - REDIS_SECRET=yh93gjso64
    networks:
      - docker-network
      - nginx

networks:
  docker-network:
    external: true
    name: database_docker-network
  nginx:
    driver: bridge